#!/usr/bin/env bash
# This script display information about subdomains.

printdomain () { 
    declare -a arr=("www" "lb-01" "web-01" "web-02")
    if [ $# -eq 1 ]
        then
            for i in "${arr[@]}"
            do
                echo -n "The subdomain $i"
                dig "$i"'.'"$1" | grep -A1 'ANSWER SECTION:'| tail -1 | awk '{ print " is a " $4 " record and points to " $5}'
            done
    else
        echo -n "The subdomain $2"
        dig "$2"'.'"$1" | grep -A1 'ANSWER SECTION:'| tail -1 | awk '{ print " is a " $4 " record and points to " $5}'
    fi
}
printdomain "$@"
