#!/usr/bin/env bash
# This script configure a new Ubuntu machine.
sudo apt update
sudo apt install -y nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" | sudo tee '/var/www/html/index.nginx-debian.html'
service nginx start
