#!/usr/bin/env bash
# This script configure a new Ubuntu machine.
sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
echo 'Holberton School' | sudo tee '/var/www/html/index.nginx-debian.html'
service nginx restart
