#!/usr/bin/env bash
# This script configure a new Ubuntu machine.
sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
echo 'Holberton School' | sudo tee '/var/www/html/index.html'
new_string="server_name _;\n\t\trewrite /redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i 's|server_name _;|'"$new_string"'|' /etc/nginx/sites-enabled/default
service nginx restart
