#!/usr/bin/env bash
# script that generates a MySQL dump and creates a compressed archive out of it.
mysqldump --user=root --password="$1" --all-databases > backup.sql
tar -czf $(date +%d-%m-%Y).tar.gz backup.sql
