#!/usr/bin/env bash
# Ubuntu container’s Nginx installation from listening on port 80
sudo sed -i "21,22d" /etc/nginx/sites-enabled/default
sudo sed -i "21i \\\tlisten 80 default_server;" /etc/nginx/sites-enabled/default
sudo sed -i "22i \\\tlisten [::]:80 default_server ipv6only=on;" /etc/nginx/sites-enabled/default
sudo service nginx restart
