#!/usr/bin/env bash
# This script is displaying "To infinity and beyond" indefinitely.
trap "echo 'I am invincible!!!'" SIGTERM
count=1
while [ $count ]; do
    echo "To infinity and beyond"
    sleep 2
    let "count+=1"
done;
