#!/usr/bin/env bash
# displays Holberton School 10 times, but for the 9th iteration, displays Holberton School and then Hi on a new line.
count=1
while [ $count -le 10 ]; do
    echo "Holberton School"
    if [ $count -eq 9 ]
    then
        echo "Hi"
    fi
    let "count+=1"
done;
