#!/usr/bin/env bash
# This script displays listening ports
cp /etc/hosts /etc/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/g' /etc/hosts.new
sed -i '1i\8.8.8.8 facebook.com' /etc/hosts.new
cp -f /etc/hosts.new /etc/hosts
