#!/usr/bin/env bash
# This script Run Nginx as Nginx.
pkill apache2
chmod 700 /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/nginx.conf
sudo sed -i 's|80|8080|' /etc/nginx/sites-enabled/default
sudo -u nginx service nginx start
